apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vue-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vue-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5
